
typedef enum {
   CAMERA_STRUCT  = 0,
   HOUSE_STRUCT,
   STREET_STRUCT, 
   NEIGHBORHOOD_STRUCT,
   FAKE_HOUSE_STRUCT,
   FAKE_NEIGHBORHOOD_TOP_STRUCT,  
   FAKE_NEIGHBORHOOD_SIDE_STRUCT,
   GRID_STRUCT,   
   TEXT_STRUCT,   
   FAKE_HOUSE_TOP_STRUCT,
   FAKE_HOUSE_SIDE_STRUCT,
   AXES_STRUCT,   
   CHIMNEY_STRUCT,        
   SPHERE_STRUCT,        

   NUMBER_OF_STRUCTS
} structID;
